branches:
  only:
  - master
  - "/^v.*$/"
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
language: python
matrix:
  include:
  - python: 3.8
  - python: 3.7
  - python: 3.6
  - python: 3.5
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - python3 -m venv env
      - source env/bin/activate
  - services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
  - services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/.manylinux-install.sh
    after_success:
    - if [[ $TRAVIS_TAG ]]; then pip install twine && twine upload -u datamade.wheelbuilder
      -p $PYPIPASSWORD --skip-existing wheelhouse/*; fi
    - exit 0
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -e .
script:
- pytest tests
deploy:
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
  distributions: bdist_wheel
  password: "$PYPIPASSWORD"
- provider: pypi
  skip_cleanup: true
  user: datamade.wheelbuilder
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
  distributions: sdist
  password: "$PYPIPASSWORD"
env:
  global:
  - secure: DxezFbZgFhL7EuIkwJqDDX7lu2aP+JJ9hK5rIIqe5mq0aweZykTF8PIgf0H9J5/Kn5duL6rnLoVuqj1IKnYVOzHpUFO6T/k0W84HjuqfyRbCNuNlJS1shuCPQd4jmQI2VfQUmJsdmYRYTBUhdHpOkKhZ1vR1s2PE9mKEr4ZjUVs=
